#ifndef SETTINGS_H
#define SETTINGS_H

// ===== Controller Settings
#define RF_CONTROLLER_ID 0
#define RF_DRONE_ID 3
#define CONTROLLER_ANALOG_MAX_VALUE 512

// ===== Motor Settings
#define MOTOR_MAX_SPEED 255
#define MOTOR_COUNT 4
#define MOTOR_FRONT_LEFT 0
#define MOTOR_FRONT_RIGHT 1
#define MOTOR_BACK_LEFT 2
#define MOTOR_BACK_RIGHT 3
#define MOTOR_ADJUSTMENT_CONSTANT 100
#define MOTOR_SMOOTHING_FACTOR 0.9

// ==== Sensor Settings
#define ALTITUDE 50.0

#define ACCELEROMETER_SMOOTHING_FACTOR 0.8
#define GYRO_SMOOTHING_FACTOR 0.8
#define TEMPERATURE_SMOOTHING_FACTOR 0.9
#define PRESSURE_SMOOTHING_FACTOR 0.9

#endif